services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: money_note
      POSTGRES_USER: money_note
      POSTGRES_PASSWORD: money_note_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
