import { GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut, type User } from 'firebase/auth';
import { FormEvent, useEffect, useState } from 'react';
import { firebaseAuth } from './firebase';

type TransactionType = 'income' | 'expense';
type Transaction = { id: number; date: string; type: TransactionType; amount: number; category: string; memo: string | null };
type CategoryBreakdown = { category: string; amount: number; percentage: number };
type MonthlySummary = { income: number; expense: number; balance: number; categories: CategoryBreakdown[] };
const categories = ['食費', '日用品', '交通', '住居', '光熱費', '通信', '娯楽', '医療', '教育', 'その他', '給与', '臨時収入'];
const now = new Date(); const initialMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
const yen = (value: number) => new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 }).format(value);
const blank = (date = `${initialMonth}-01`) => ({ date, type: 'expense' as TransactionType, amount: '', category: '食費', memo: '' });

function MoneyNote({ user }: { user: User }) {
  const [month, setMonth] = useState(initialMonth); const [rows, setRows] = useState<Transaction[]>([]); const [summary, setSummary] = useState<MonthlySummary>({ income: 0, expense: 0, balance: 0, categories: [] });
  const [form, setForm] = useState(blank()); const [editing, setEditing] = useState<number | null>(null); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  async function apiFetch(input: RequestInfo | URL, init?: RequestInit) { const token = await user.getIdToken(); const headers = new Headers(init?.headers); headers.set('Authorization', `Bearer ${token}`); return fetch(input, { ...init, headers }); }
  async function fetchData(targetMonth = month) { setLoading(true); setError(''); try { const [transactionsResponse, summaryResponse] = await Promise.all([apiFetch(`/api/transactions?month=${targetMonth}`), apiFetch(`/api/summary?month=${targetMonth}`)]); if (!transactionsResponse.ok || !summaryResponse.ok) throw new Error('データを取得できませんでした。'); setRows(await transactionsResponse.json()); setSummary(await summaryResponse.json()); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } finally { setLoading(false); } }
  useEffect(() => { fetchData(); setForm(blank(`${month}-01`)); setEditing(null); }, [month]);
  function shiftMonth(diff: number) { const date = new Date(`${month}-01T00:00:00`); date.setMonth(date.getMonth() + diff); setMonth(`${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); const payload = { ...form, amount: Number(form.amount) }; try { const response = await apiFetch(editing ? `/api/transactions/${editing}` : '/api/transactions', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? '保存できませんでした。'); setMessage(editing ? '記録を更新しました。' : '記録を追加しました。'); setEditing(null); setForm(blank(`${month}-01`)); await fetchData(); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } }
  function edit(row: Transaction) { setEditing(row.id); setForm({ date: row.date, type: row.type, amount: String(row.amount), category: row.category, memo: row.memo ?? '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function remove(id: number) { if (!window.confirm('この記録を削除しますか？')) return; setError(''); try { const response = await apiFetch(`/api/transactions/${id}`, { method: 'DELETE' }); if (!response.ok) { const data = await response.json(); throw new Error(data.error ?? '削除できませんでした。'); } setMessage('記録を削除しました。'); await fetchData(); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } }
  return <main><header><div><p className="eyebrow">MONEY NOTE</p><h1>わたしの家計簿</h1></div><div className="header-actions"><div className="month"><button onClick={() => shiftMonth(-1)} aria-label="前月">‹</button><input aria-label="対象月" type="month" value={month} onChange={(e) => setMonth(e.target.value)} /><button onClick={() => shiftMonth(1)} aria-label="翌月">›</button></div><div className="user-menu">{user.photoURL && <img src={user.photoURL} alt="" referrerPolicy="no-referrer" />}<button onClick={() => signOut(firebaseAuth)}>ログアウト</button></div></div></header>
    <section className="summary" aria-label="月次サマリー"><article><span>収入</span><strong className="income">{yen(summary.income)}</strong></article><article><span>支出</span><strong className="expense">{yen(summary.expense)}</strong></article><article><span>収支</span><strong className={summary.balance >= 0 ? 'income' : 'expense'}>{yen(summary.balance)}</strong></article></section>
    <div className="grid"><section className="card form-card"><h2>{editing ? '記録を編集' : '記録を追加'}</h2><form onSubmit={submit}><label>日付<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label>種別<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as TransactionType, category: e.target.value === 'income' ? '給与' : '食費' })}><option value="expense">支出</option><option value="income">収入</option></select></label><label>金額<input required min="1" step="1" type="number" inputMode="numeric" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label>カテゴリ<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="wide">メモ（任意）<input maxLength={200} value={form.memo} onChange={(e) => setForm({ ...form, memo: e.target.value })} /></label><div className="actions"><button className="primary">{editing ? '更新する' : '追加する'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(blank(`${month}-01`)); }}>キャンセル</button>}</div></form>{message && <p className="message">{message}</p>}{error && <p className="error" role="alert">{error}</p>}</section>
      <section className="card"><h2>カテゴリ別支出</h2>{summary.categories.length === 0 ? <p className="empty">この月の支出はまだありません。</p> : <ul className="breakdown">{summary.categories.map((item) => <li key={item.category}><div><span>{item.category}</span><small>{item.percentage}%</small></div><strong>{yen(item.amount)}</strong><i><b style={{ width: `${item.percentage}%` }} /></i></li>)}</ul>}</section></div>
    <section className="card history"><h2>{month.replace('-', '年')}月の記録</h2>{loading ? <p className="empty">読み込み中…</p> : rows.length === 0 ? <p className="empty">この月の記録はまだありません。</p> : <div className="table-wrap"><table><thead><tr><th>日付</th><th>カテゴリ / メモ</th><th>種別</th><th>金額</th><th aria-label="操作" /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.date.slice(5).replace('-', '/')}</td><td><b>{row.category}</b>{row.memo && <small>{row.memo}</small>}</td><td>{row.type === 'income' ? '収入' : '支出'}</td><td className={row.type}>{row.type === 'expense' ? '-' : '+'}{yen(row.amount)}</td><td><button onClick={() => edit(row)}>編集</button><button className="delete" onClick={() => remove(row.id)}>削除</button></td></tr>)}</tbody></table></div>}</section></main>;
}

export default function App() {
  const [user, setUser] = useState<User | null | undefined>(undefined);
  const [loginError, setLoginError] = useState('');
  useEffect(() => onAuthStateChanged(firebaseAuth, setUser), []);
  async function login() { setLoginError(''); try { await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); } catch (error) { setLoginError(error instanceof Error ? error.message : 'ログインに失敗しました。'); } }
  if (user === undefined) return <main className="auth-page"><p>ログイン状態を確認中…</p></main>;
  if (!user) return <main className="auth-page"><section className="auth-card"><p className="eyebrow">MONEY NOTE</p><h1>わたしの家計簿</h1><p>Googleアカウントでログインして始めましょう。</p><button className="primary google-login" onClick={login}>Googleでログイン</button>{loginError && <p className="error" role="alert">{loginError}</p>}</section></main>;
  return <MoneyNote user={user} />;
}