import { GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut, type User } from 'firebase/auth';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { firebaseAuth } from './firebase';

type TransactionType = 'income' | 'expense';
type Transaction = { id: number; date: string; type: TransactionType; amount: number; category: string; memo: string | null };
type CategoryBreakdown = { category: string; amount: number; percentage: number };
type MonthlySummary = { income: number; expense: number; balance: number; categories: CategoryBreakdown[] };
const categories = ['食費', '日用品', '交通', '住居', '光熱費', '通信', '娯楽', '医療', '教育', 'その他', '給与', '臨時収入'];
const now = new Date();
const initialMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
const yen = (value: number) => new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY', maximumFractionDigits: 0 }).format(value);
const blank = (date = `${initialMonth}-01`) => ({ date, type: 'expense' as TransactionType, amount: '', category: '食費', memo: '' });
const categoryIcon = (category: string) => ({ 食費: '🍽', 日用品: '◈', 交通: '↗', 住居: '⌂', 光熱費: 'ϟ', 通信: '◌', 娯楽: '✦', 医療: '+', 教育: '▤', その他: '•••', 給与: '¥', 臨時収入: '＋' }[category] ?? '◌');

function MoneyNote({ user }: { user: User }) {
  const [month, setMonth] = useState(initialMonth);
  const [rows, setRows] = useState<Transaction[]>([]);
  const [summary, setSummary] = useState<MonthlySummary>({ income: 0, expense: 0, balance: 0, categories: [] });
  const [form, setForm] = useState(blank());
  const [editing, setEditing] = useState<number | null>(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  const monthLabel = useMemo(() => new Intl.DateTimeFormat('ja-JP', { year: 'numeric', month: 'long' }).format(new Date(`${month}-01T00:00:00`)), [month]);
  const savingRate = summary.income > 0 ? Math.max(0, Math.round((summary.balance / summary.income) * 100)) : 0;

  async function apiFetch(input: RequestInfo | URL, init?: RequestInit) { const token = await user.getIdToken(); const headers = new Headers(init?.headers); headers.set('Authorization', `Bearer ${token}`); return fetch(input, { ...init, headers }); }
  async function fetchData(targetMonth = month) { setLoading(true); setError(''); try { const [transactionsResponse, summaryResponse] = await Promise.all([apiFetch(`/api/transactions?month=${targetMonth}`), apiFetch(`/api/summary?month=${targetMonth}`)]); if (!transactionsResponse.ok || !summaryResponse.ok) throw new Error('データを取得できませんでした。'); setRows(await transactionsResponse.json()); setSummary(await summaryResponse.json()); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } finally { setLoading(false); } }
  useEffect(() => { fetchData(); setForm(blank(`${month}-01`)); setEditing(null); }, [month]);
  function shiftMonth(diff: number) { const date = new Date(`${month}-01T00:00:00`); date.setMonth(date.getMonth() + diff); setMonth(`${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); const payload = { ...form, amount: Number(form.amount) }; try { const response = await apiFetch(editing ? `/api/transactions/${editing}` : '/api/transactions', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? '保存できませんでした。'); setMessage(editing ? '記録を更新しました。' : '記録を追加しました。'); setEditing(null); setForm(blank(`${month}-01`)); await fetchData(); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } }
  function edit(row: Transaction) { setEditing(row.id); setForm({ date: row.date, type: row.type, amount: String(row.amount), category: row.category, memo: row.memo ?? '' }); document.querySelector('.entry-card')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }
  async function remove(id: number) { if (!window.confirm('この記録を削除しますか？')) return; setError(''); try { const response = await apiFetch(`/api/transactions/${id}`, { method: 'DELETE' }); if (!response.ok) { const data = await response.json(); throw new Error(data.error ?? '削除できませんでした。'); } setMessage('記録を削除しました。'); await fetchData(); } catch (e) { setError(e instanceof Error ? e.message : 'エラーが発生しました。'); } }

  return <main className="app-shell">
    <header className="topbar"><a className="brand" href="/"><span className="brand-mark">M</span><span>Money <b>Note</b></span></a><div className="topbar-right"><p className="sync-status"><i />すべて保存済み</p><div className="user-menu">{user.photoURL ? <img src={user.photoURL} alt="" referrerPolicy="no-referrer" /> : <span className="avatar-fallback">{user.displayName?.slice(0, 1) ?? 'U'}</span>}<div className="user-copy"><b>{user.displayName?.split(' ')[0] ?? 'ユーザー'}</b><button onClick={() => signOut(firebaseAuth)}>ログアウト</button></div></div></div></header>
    <section className="page-heading"><div><p className="eyebrow">PERSONAL FINANCE</p><h1>おかえりなさい、{user.displayName?.split(' ')[0] ?? 'あなた'}さん</h1><p className="heading-sub">日々のお金の流れを、心地よく見える化しましょう。</p></div><div className="month-control"><button onClick={() => shiftMonth(-1)} aria-label="前月">←</button><label><span>表示する月</span><input aria-label="対象月" type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label><button onClick={() => shiftMonth(1)} aria-label="翌月">→</button></div></section>
    <section className="hero-summary" aria-label="月次サマリー"><div className="hero-balance"><div className="balance-label"><span>今月の収支</span><span className="month-pill">{monthLabel}</span></div><strong>{yen(summary.balance)}</strong><p>{summary.balance >= 0 ? 'この調子で、ゆとりある毎日を。' : '今月の支出を少しだけ見直してみましょう。'}</p><div className="saving-meter"><span>貯蓄率</span><b>{savingRate}%</b><i><em style={{ width: `${Math.min(savingRate, 100)}%` }} /></i></div></div><div className="hero-stats"><article><span className="stat-icon income-icon">↗</span><div><small>収入</small><strong>{yen(summary.income)}</strong><p>今月の入金額</p></div></article><article><span className="stat-icon expense-icon">↘</span><div><small>支出</small><strong>{yen(summary.expense)}</strong><p>今月の利用額</p></div></article></div></section>
    <div className="dashboard-grid"><section className="panel entry-card"><div className="panel-heading"><div><p className="section-kicker">QUICK ENTRY</p><h2>{editing ? '記録を編集' : '新しい記録を追加'}</h2></div>{editing && <span className="editing-badge">編集中</span>}</div><form onSubmit={submit}><label>日付<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label>種別<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as TransactionType, category: e.target.value === 'income' ? '給与' : '食費' })}><option value="expense">支出</option><option value="income">収入</option></select></label><label className="amount-field">金額<div className="amount-input"><span>¥</span><input required min="1" step="1" type="number" inputMode="numeric" placeholder="0" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></div></label><label>カテゴリ<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label className="wide">メモ <small>任意</small><input maxLength={200} placeholder="何に使ったかメモしておく" value={form.memo} onChange={(e) => setForm({ ...form, memo: e.target.value })} /></label><div className="actions"><button className="primary">{editing ? '変更を保存' : '記録を追加'} <span>→</span></button>{editing && <button className="secondary" type="button" onClick={() => { setEditing(null); setForm(blank(`${month}-01`)); }}>キャンセル</button>}</div></form>{message && <p className="message">✓ {message}</p>}{error && <p className="error" role="alert">{error}</p>}</section>
      <section className="panel categories-card"><div className="panel-heading"><div><p className="section-kicker">SPENDING INSIGHT</p><h2>カテゴリ別支出</h2></div><span className="total-caption">合計 {yen(summary.expense)}</span></div>{summary.categories.length === 0 ? <div className="empty-state"><span>◎</span><p>支出を記録すると<br />ここに内訳が表示されます。</p></div> : <ul className="breakdown">{summary.categories.map((item) => <li key={item.category}><span className="category-icon">{categoryIcon(item.category)}</span><div className="category-data"><div><b>{item.category}</b><small>{item.percentage}%</small></div><i><em style={{ width: `${item.percentage}%` }} /></i></div><strong>{yen(item.amount)}</strong></li>)}</ul>}</section></div>
    <section className="panel history"><div className="panel-heading"><div><p className="section-kicker">ACTIVITY</p><h2>{monthLabel}の記録</h2></div><span className="record-count">{rows.length} 件の記録</span></div>{loading ? <div className="empty-state"><span className="loader" /><p>読み込み中です…</p></div> : rows.length === 0 ? <div className="empty-state"><span>◌</span><p>まだ記録がありません。<br />最初のひとつを追加してみましょう。</p></div> : <div className="transaction-list">{rows.map((row) => <article className="transaction" key={row.id}><div className={`transaction-icon ${row.type}`}>{row.type === 'income' ? '↗' : categoryIcon(row.category)}</div><div className="transaction-info"><b>{row.category}</b><span>{row.memo || 'メモなし'} <i>·</i> {row.date.slice(5).replace('-', '/')}</span></div><span className={`type-chip ${row.type}`}>{row.type === 'income' ? '収入' : '支出'}</span><strong className={row.type}>{row.type === 'expense' ? '−' : '+'}{yen(row.amount)}</strong><div className="row-actions"><button onClick={() => edit(row)}>編集</button><button className="delete" onClick={() => remove(row.id)} aria-label={`${row.category}を削除`}>削除</button></div></article>)}</div>}</section>
  </main>;
}

export default function App() {
  const [user, setUser] = useState<User | null | undefined>(undefined);
  const [loginError, setLoginError] = useState('');
  useEffect(() => onAuthStateChanged(firebaseAuth, setUser), []);
  async function login() { setLoginError(''); try { await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); } catch (error) { setLoginError(error instanceof Error ? error.message : 'ログインに失敗しました。'); } }
  if (user === undefined) return <main className="auth-page"><div className="auth-orb orb-one" /><div className="auth-orb orb-two" /><p className="loading-copy">Money Note を準備しています…</p></main>;
  if (!user) return <main className="auth-page"><div className="auth-orb orb-one" /><div className="auth-orb orb-two" /><section className="auth-card"><a className="brand" href="/"><span className="brand-mark">M</span><span>Money <b>Note</b></span></a><div className="auth-copy"><p className="eyebrow">YOUR MONEY, CLEARLY</p><h1>お金の記録を、<br />もっと心地よく。</h1><p>毎日の収支をひとつにまとめて、<br />あなたらしいお金の使い方を見つけましょう。</p></div><button className="google-login" onClick={login}><span className="google-g">G</span>Google で続ける <i>→</i></button><p className="auth-note">ログインすると、安全にデータが保存されます。</p>{loginError && <p className="error" role="alert">{loginError}</p>}</section></main>;
  return <MoneyNote user={user} />;
}
